---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-po
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm 
        - secretRef:
            name: bgg-secret
        ports:
        - name: bggapp-port
          containerPort: 3000

---
apiVersion: v1 
kind: Service 
metadata:
  name: bggapp-svc 
  labels:
    name: bggapp-svc 
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
  - port: 80 
    targetPort: bggapp-port

---
apiVersion: v1
kind: ConfigMap
metadata:
   name: bgg-cm
   labels:
      name: bgg-cm
data:
   BGG_DB_USER: root
   BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret

data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=